export { default as home } from './home.vue'
export { default as userAvatar } from './userAvatar.vue'
export { default as exit } from './exit.vue'
export { default as triangle } from './triangle.vue'
export { default as star } from './star.vue'
export { default as fork } from './fork.vue'
export { default as close } from './close.vue'
